apiVersion: v1
kind: Namespace
metadata:
  name: openshift-lifecycle-agent
  labels:
    openshift.io/cluster-monitoring: "true"
  annotations:
    workload.openshift.io/allowed: management
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: lifecycle-agent-operatorgroup
  namespace: openshift-lifecycle-agent
spec:
  targetNamespaces:
  - openshift-lifecycle-agent
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: lifecycle-agent
  namespace: openshift-lifecycle-agent
spec:
  channel: "stable"
  name: lifecycle-agent
  #  source: cs-redhat-operator-index
  source: cs-prega-operator-index-v4-18
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
