apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: performance-patch
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
  - data: |
      [main]
      summary=Configuration changes profile inherited from performance created tuned
      include=openshift-node-performance-openshift-node-performance-profile
      [sysctl]
      # When using the standard (non-realtime) kernel, remove the kernel.timer_migration override from the [sysctl] section
      # kernel.timer_migration=0
      [scheduler]
      group.ice-ptp=0:f:10:*:ice-ptp.*
      group.ice-gnss=0:f:10:*:ice-gnss.*
      [service]
      service.stalld=start,enable
      service.chronyd=stop,disable
    name: performance-patch
  recommend:
  - machineConfigLabels:
      machineconfiguration.openshift.io/role: master
    priority: 19
    profile: performance-patch
