apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: multiclusterengine
spec:
  availabilityConfig: Basic
  targetNamespace: multicluster-engine
  overrides:
    components:
    - enabled: true
      name: assisted-service
    - enabled: true
      name: cluster-lifecycle
    - enabled: true
      name: cluster-manager
    - enabled: true
      name: discovery
    - enabled: true
      name: hive
    - enabled: true
      name: server-foundation
    - enabled: true
      name: cluster-proxy-addon
    - enabled: true
      name: local-cluster
    - enabled: true
      name: hypershift-local-hosting
    - enabled: true
      name: hypershift
    - enabled: true
      name: managedserviceaccount
    - enabled: false
      name: image-based-install-operator-preview
    - enabled: true
      name: console-mce
