apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: multiclusterengine
spec:
  availabilityConfig: Basic
  targetNamespace: multicluster-engine
  overrides:
    components:
    - name: image-based-install-operator
      enabled: true
    - name: hypershift
      enabled: false
    - name: hypershift-local-hosting
      enabled: false
